services:
  - type: web
    name: datathon-passos-magicos
    runtime: docker
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: production
      - key: API_URL
        value: http://127.0.0.1:8080/api
      - key: MODEL_PATH
        value: /app/app/models/model.pkl
      - key: DATASET_PATH
        value: /app/app/data/raw/BASE DE DADOS PEDE 2024 - DATATHON.xlsx
      - key: ARTIFACTS_DIR
        value: /app/app/artifacts
      - key: KEEP_ALIVE_INTERVAL
        value: 600
      - key: MLFLOW_TRACKING_URI
        value: file:./mlruns
    healthCheckPath: /health